CREATE DATABASE CASTELLO_RELACIONAMENTOS;
USE CASTELLO_RELACIONAMENTOS;

CREATE TABLE PRODUTOS (
    ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_PRODUTO VARCHAR(100) NOT NULL
);
CREATE TABLE ESTOQUE (
    ID_ESTOQUE INT AUTO_INCREMENT PRIMARY KEY,
    ID_PRODUTO INT NOT NULL UNIQUE,
    QUANTIDADE INT NOT NULL,
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
);

CREATE TABLE CLIENTES (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME_CLIENTE VARCHAR(60) NOT NULL
);

CREATE TABLE PEDIDOS (
    ID_PEDIDO INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
    DATA_PEDIDO DATETIME NOT NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

CREATE TABLE FORNECEDORES (
    ID_FORNECEDOR INT AUTO_INCREMENT PRIMARY KEY,
    NOME_FORNECEDOR VARCHAR(60) NOT NULL
);

CREATE TABLE FORNECEDOR_PRODUTO (
    ID_FORNECEDOR INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    PRIMARY KEY (ID_FORNECEDOR, ID_PRODUTO),
    FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDORES(ID_FORNECEDOR),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
);

SELECT * FROM PRODUTOS;

INSERT INTO PRODUTOS (NOME_PRODUTO) VALUES ('Blusa');

-- Desafio Cardinalidades
-- QUESTÃO 1
-- CATEGORIA --PERTENCE --PRODUTO
--1,N                      1,1

-- QUESTÃO 2
--FUNCIONARIO --REGISTRA --PEDIDO
--1,N                          1,1

-- QUESTÃO 3
--FORNECEDOR --COMERCIALIZA --PRODUTOS
--1,N                          1,N

-- QUESTÃO 4
--MESA --RESERVA --CLIENTE
-- 0,N                1,1

-- QUESTÃO 5
--PEDIDO --POSSUI --ITEM
-- 1,N                  1,1